### ISSUE TITLE
v0.9.0 does not build with Rust 1.80

### ISSUE THREAD

**Issue by matrixbot** [element-hq/matrix-authentication-service#3088]
*This issue was originally created by [**@teutat3s**](https://github.com/teutat3s) at <https://github.com/matrix-org/matrix-authentication-service/issues/3088>.*

[alyssais discovered](https://github.com/NixOS/nixpkgs/issues/332957) that Rust 1.80.0 contains a couple of changes that break the build for `matrtix-authentication-service`. I'm opening this issue to coordinate efforts to make `matrtix-authentication-service` ready for 1.80.0.

Citing the linked issue:
> Figure out what's broken. Usually, but not always, this is that the "time" crate needs to be updated.

```
   Compiling time v0.3.34
error[E0282]: type annotations needed for `Box<_>`
```

It looks like the `time` crate was already bumped to `v0.3.36`, so all that would be needed here should be a new release.
